### ISSUE TITLE
Publish on npm

### ISSUE THREAD

**Issue by carlbennettnz** [carlbennettnz/json-api-knex-adapter#1]
@ethanresnick I think you mentioned a while back you wanted me to put this under `@json-api/knex-adapter`. If so, could you hook me up with the right npm permissions please?

**Comment by ethanresnick** [comment]
Sure! What's your npm username?

**Comment by carlbennettnz** [comment]
Thanks :) cbnz

**Comment by ethanresnick** [comment]
Invited!

**Comment by carlbennettnz** [comment]
Beta published! Thanks for your help!
